/**
 * Сид календаря пространства «Дела» (этап 8, docs/SCENARIOS.md §2, §4),
 * включая заседание 5 августа: дата считается относительно `new Date()`
 * через `daysFromNow(12)` — тем же смещением, что и `casePosition`/
 * `morningDigest` (`hearingAt = daysFromNow(12, '11:00')`), поэтому не
 * протухнет при повторном запуске демо в тот же день. Разброс по срочности
 * — от просроченных до дальних — для проверки таймлайна (docs/UX.md §5).
 */
import type { CalendarEvent } from '@/types/domain';
import {
  CARD,
  DOC,
  srcA40ExpertConclusion,
  srcA40ResponseArg1,
  srcA40RulingDate,
  srcA40RulingEvidence,
  srcA41Subject,
  srcPractice14,
} from '@/core/agent/scenarios/refs';
import { daysFromNow } from '@/core/agent/scenarios/dates';

export const litigationEvents: CalendarEvent[] = [
  {
    id: 'evt-lit-a40-ruling-issued',
    workspaceId: 'litigation',
    kind: 'reminder',
    title: 'Получено определение суда о принятии иска по делу №А40-118742/2026',
    at: daysFromNow(-22),
    priority: 'P3',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    sources: [srcA40RulingDate()],
  },
  {
    id: 'evt-lit-a40-response-received',
    workspaceId: 'litigation',
    kind: 'reminder',
    title: 'Получен отзыв ответчика по делу №А40-118742/2026',
    at: daysFromNow(-5),
    priority: 'P2',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    sources: [srcA40ResponseArg1()],
  },
  {
    id: 'evt-lit-a40-expert-received',
    workspaceId: 'litigation',
    kind: 'reminder',
    title: 'Получено заключение эксперта по делу №А40-118742/2026',
    at: daysFromNow(-3),
    priority: 'P2',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    sources: [srcA40ExpertConclusion()],
  },
  {
    id: 'evt-lit-a40-evidence-filing',
    workspaceId: 'litigation',
    kind: 'deadline',
    title: 'Заявить ходатайство об истребовании доказательств по делу №А40-118742/2026',
    at: daysFromNow(3),
    priority: 'P1',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    relatedCardId: CARD.EVIDENCE_A40,
    sources: [srcA40RulingEvidence()],
  },
  {
    id: 'evt-lit-a40-filing',
    workspaceId: 'litigation',
    kind: 'deadline',
    title: 'Подать возражения на отзыв по делу №А40-118742/2026',
    at: daysFromNow(5),
    priority: 'P1',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    relatedCardId: CARD.FILING_A40,
    sources: [srcA40RulingDate()],
  },
  {
    id: 'evt-lit-a40-expert-meeting',
    workspaceId: 'litigation',
    kind: 'meeting',
    title: 'Совещание по заключению эксперта перед заседанием',
    at: daysFromNow(6, '14:00'),
    durationMin: 30,
    location: 'Переговорная 2',
    priority: 'P2',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
  },
  {
    id: 'evt-lit-a40-hearing',
    workspaceId: 'litigation',
    kind: 'hearing',
    title: 'Судебное заседание по делу №А40-118742/2026',
    at: daysFromNow(12, '11:00'),
    durationMin: 90,
    location: 'Арбитражный суд г. Москвы',
    priority: 'P0',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    relatedCardId: CARD.HEARING_A40,
    sources: [srcA40RulingDate()],
  },
  {
    id: 'evt-lit-a41-evidence-deadline',
    workspaceId: 'litigation',
    kind: 'deadline',
    title: 'Подать доказательства правомерности отказа по делу №А41-9930/2026',
    at: daysFromNow(15),
    priority: 'P2',
    subjectRef: { kind: 'case', id: DOC.CASE_A41_CLAIM, label: 'Дело №А41-9930/2026' },
    sources: [srcA41Subject()],
  },
  {
    id: 'evt-lit-a41-hearing',
    workspaceId: 'litigation',
    kind: 'hearing',
    title: 'Предварительное заседание по делу №А41-9930/2026',
    at: daysFromNow(20, '10:00'),
    durationMin: 60,
    location: 'Арбитражный суд Московской области',
    priority: 'P2',
    subjectRef: { kind: 'case', id: DOC.CASE_A41_CLAIM, label: 'Дело №А41-9930/2026' },
    relatedCardId: 'card-hearing-a41',
    sources: [srcA41Subject()],
  },
  {
    id: 'evt-lit-practice-review',
    workspaceId: 'litigation',
    kind: 'reminder',
    title: 'Проверить обновления практики ВС РФ по срокам исковой давности',
    at: daysFromNow(30),
    priority: 'P3',
    subjectRef: { kind: 'case', id: DOC.CASE_A40_CLAIM, label: 'Дело №А40-118742/2026' },
    sources: [srcPractice14()],
  },
];
