/**
 * Сид календаря пространства «Обязательства» (этап 8, docs/SCENARIOS.md §2,
 * §4). Разброс по срочности — просроченные, сегодня, ближайшие, дальние —
 * чтобы таймлайн и цветовое кодирование срочности (docs/UX.md §5) было на
 * чём проверить. Все даты — относительно `new Date()` через `daysFromNow`.
 */
import type { CalendarEvent } from '@/types/domain';
import {
  CARD,
  DOC,
  srcLeaseIndexation,
  srcLeaseNotice,
  srcLetterVektorClaim,
  srcNda09Term,
  srcServices27Renewal,
  srcSupply118Delivery,
  srcSupply118Payment,
  srcSupply203Renewal,
} from '@/core/agent/scenarios/refs';
import { daysFromNow } from '@/core/agent/scenarios/dates';

export const obligationsEvents: CalendarEvent[] = [
  {
    id: 'evt-obl-poa-renewal',
    workspaceId: 'obligations',
    kind: 'reminder',
    title: 'Обновить доверенность представителя по договорам поставки',
    at: daysFromNow(-2),
    priority: 'P2',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_118, label: 'Договор поставки №118/П' },
  },
  {
    id: 'evt-obl-lease-44-notice',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Направить отказ от пролонгации по №44-АР',
    at: daysFromNow(1),
    priority: 'P0',
    subjectRef: { kind: 'contract', id: DOC.LEASE_44, label: 'Договор №44-АР' },
    relatedCardId: CARD.RENEWAL_44,
    sources: [srcLeaseNotice()],
  },
  {
    id: 'evt-obl-vektor-internal-review',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Согласовать проект ответа «Вектору» с финдиректором',
    at: daysFromNow(0, '17:00'),
    priority: 'P1',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_118, label: 'Договор поставки №118/П' },
    sources: [srcSupply118Delivery()],
  },
  {
    id: 'evt-obl-lease-review-meeting',
    workspaceId: 'obligations',
    kind: 'meeting',
    title: 'Встреча с ООО «Прайм Ритейл» по условиям аренды',
    at: daysFromNow(2, '15:00'),
    durationMin: 45,
    location: 'Видеозвонок',
    priority: 'P2',
    subjectRef: { kind: 'contract', id: DOC.LEASE_44, label: 'Договор №44-АР' },
  },
  {
    id: 'evt-obl-vektor-response',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Ответить «Вектору» по повышению цены',
    at: daysFromNow(7),
    priority: 'P1',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_118, label: 'Договор поставки №118/П' },
    relatedCardId: CARD.VEKTOR_PRICE,
    sources: [srcLetterVektorClaim(), srcSupply118Delivery()],
  },
  {
    id: 'evt-obl-payment-4471',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Оплатить счёт №4471 по договору поставки №118/П',
    at: daysFromNow(10),
    priority: 'P2',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_118, label: 'Договор поставки №118/П' },
    relatedCardId: CARD.PAYMENT_4471,
    sources: [srcSupply118Payment()],
  },
  {
    id: 'evt-obl-renewal-27-notice',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Решить по автопролонгации №27-У',
    at: daysFromNow(23),
    priority: 'P2',
    subjectRef: { kind: 'contract', id: DOC.SERVICES_27, label: 'Договор №27-У' },
    relatedCardId: CARD.RENEWAL_27,
    sources: [srcServices27Renewal()],
  },
  {
    id: 'evt-obl-payment-8825',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Оплатить счёт №8825 по договору поставки №118/П',
    at: daysFromNow(25),
    priority: 'P3',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_118, label: 'Договор поставки №118/П' },
    relatedCardId: 'card-payment-8825',
    sources: [srcSupply118Payment()],
  },
  {
    id: 'evt-obl-renewal-203-notice',
    workspaceId: 'obligations',
    kind: 'deadline',
    title: 'Решить по автопролонгации №203/П',
    at: daysFromNow(28),
    priority: 'P2',
    subjectRef: { kind: 'contract', id: DOC.SUPPLY_203, label: 'Договор №203/П' },
    relatedCardId: CARD.RENEWAL_203,
    sources: [srcSupply203Renewal()],
  },
  {
    id: 'evt-obl-indexation-check',
    workspaceId: 'obligations',
    kind: 'reminder',
    title: 'Проверить индексацию арендной платы по №44-АР',
    at: daysFromNow(45),
    priority: 'P3',
    subjectRef: { kind: 'contract', id: DOC.LEASE_44, label: 'Договор №44-АР' },
    sources: [srcLeaseIndexation()],
  },
  {
    id: 'evt-obl-nda-term-check',
    workspaceId: 'obligations',
    kind: 'reminder',
    title: 'Проверить актуальность режима конфиденциальности по №09-К',
    at: daysFromNow(60),
    priority: 'P3',
    subjectRef: { kind: 'contract', id: DOC.NDA_09, label: 'Соглашение №09-К' },
    sources: [srcNda09Term()],
  },
];
